name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/FontsFree-Net-Poppins-Bold.ttf
          weight: 700
        - asset: fonts/FontsFree-Net-Poppins-Medium.ttf
          weight: 500
        - asset: fonts/FontsFree-Net-Poppins-Regular.ttf
          weight: 400
        - asset: fonts/FontsFree-Net-Poppins-SemiBold.ttf
          weight: 600
